set_property SRC_FILE_INFO {cfile:C:/Users/TechG/Desktop/folder/Coding/ObjectRecognitionSurvivalGame/Game_Code/Game_Code.srcs/constrs_1/imports/ObjectRecognitionSurvivalGame/Basys3_Master.xdc rfile:../../../Game_Code.srcs/constrs_1/imports/ObjectRecognitionSurvivalGame/Basys3_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports i_Clk]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN A18 [get_ports o_UART_TX]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B18 [get_ports i_UART_RX]
